server:
  port: 80

spring:
  application:
    name: microservice-consul-consumer-80
  cloud:
    consul:
      host: localhost
      port: 8500
      # 客户端可以设置注册到 Consul 中，也可以不注册到 Consul 注册中心中
      discovery:
        register: true