server:
  port: 3344

spring:
  application:
    name: microservice-config-server-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ittqqzz/microservice-config-repo.git
