server:
  port: 3344

spring:
  application:
    name: microservice-config-server-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ittqqzz/microservice-config-repo.git
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-config-server-3344
    prefer-ip-address: true